%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%

MODULE mAUTODESK

  PERS speeddata v107:=[107,500,5000,1000];
  PERS speeddata v333:=[333,500,5000,1000];
  PERS speeddata v36:=[36,500,5000,1000];

  PROC main()
    ! Generated by AUTODESK Fusion CAM 2605.1.18
    ! Creation date: 11/19/2025 1:49:54 PM

    ! Acceleration and jerk/ramp (percentage)
    AccSet 20,20;

    ! Configurations
    ConfJ\On;
    ConfL\Off;

    ! Load Tool
    !Tool_Change tADSK27;

    ! Spindle On/Speed
    !Spindle_ON 16500;

    pHorizontal1;

    ! Spindle Off
    !Spindle_OFF;

    ConfJ\On;
    ConfL\On;
    Stop;
  ENDPROC
ENDMODULE
